# Generated by Django 4.2 on 2023-04-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserImageRatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('selection_type', models.CharField(choices=[('interested', 'Interested'), ('rejected', 'Rejected')], default='interested', max_length=25)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_history', to='user_interests.images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
