# Generated by Django 4.2 on 2023-04-30 20:31

from django.db import migrations


def create_images(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Images = apps.get_model("user_interests", "Images")
    Images.objects.bulk_create(
        [
            Images(name="One", image_url="http://getdrawings.com/one-icon#one-icon-3.png"),
            Images(name="Two", image_url="http://getdrawings.com/free-shirt-icon#free-shirt-icon-9.png"),
            Images(name="Three", image_url="http://getdrawings.com/serial-number-icon#serial-number-icon-19.png"),
            Images(name="Four", image_url="http://getdrawings.com/serial-number-icon#serial-number-icon-18.png"),
            Images(name="Five", image_url="http://getdrawings.com/number-one-icon#number-one-icon-17.png"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('user_interests', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_images),
    ]
